services:
  bge-embedding:
    image: ${TEI_GPU_IMAGE:-ghcr.io/huggingface/text-embeddings-inference:cuda-1.9}
    gpus: all

  bge-reranker:
    image: ${TEI_GPU_IMAGE:-ghcr.io/huggingface/text-embeddings-inference:cuda-1.9}
    gpus: all
